title: Alejandro L. Ramirez
description: Hi, I'm Alejandro Ramirez, a Game Producer from Houston, TX.
logo: /assets/img/logo_256.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme