title: Alejandro L. Ramirez
description: Hi, I'm Alejandro Ramirez, a Game Producer from Houston, TX.
logo: /assets/img/portrait_animated_linear_256.gif
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme